### ISSUE TITLE
Differences between production and dev

### ISSUE THREAD

**Issue by mallowigi** [react-syntax-highlighter/react-syntax-highlighter#363] opened 2021-02-22 07:30 UTC
**Describe the bug**
Highlighting is inconsistent between production build and webpack dev build (create-react-app)

**To Reproduce**
Here's a codesandbox I made which illustrates the problem:
 
https://1j1ym.csb.app/

Compare now with the deployed version:

https://csb-1j1ym.netlify.app/

As you can see the `window` is not colored in the production build

**Expected behavior**
Highlighting must behave the same independently of the environment

**Context**:

<https://codesandbox.io/s/syntaxhighlighter-1j1ym>

Package.json:

"react": "17.0.1",
    "react-dom": "17.0.1",
    "react-scripts": "4.0.0",
    "@types/react-syntax-highlighter": "^13.5.0",
    "react-syntax-highlighter": "^15.4.3"

**Comment by jouni** [comment] 2021-03-03 10:51
I’m seeing similar behavior with tagged template literals, for example:

```typescript
render() {
  return html`<div class="foo">some html</div>`;
}
```

In development, the nested HTML is highlighted properly, but in production it’s just one string.

**Comment by jouni** [comment] 2021-03-03 11:01
This looks like a duplicate of #263

**Closed** 2021-12-23 15:39 UTC
